apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  ports:
    - port: 8761
      name: discovery-service

  type: ClusterIP
  selector:
    app: discovery-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  labels:
    app: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      name: discovery-service
      labels:
        app: discovery-service
    spec:
      priorityClassName: "high-priority"
      containers:
        - name: discovery-service
          image: jubastik/29_backend_t1
          command: [ "java", "-jar", "/app/discovery-service.jar" ]
          ports:
            - containerPort: 8761
          env:
            - name: CONFIG_SERVICE_URI
              value: "http://config-service:8888"
            - name: CONFIG_SERVICE_USER
              valueFrom:
                secretKeyRef:
                  name: config-secret
                  key: username
            - name: CONFIG_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-secret
                  key: password
            - name: DISCOVERY_SERVICE_PORT
              value: "8761"
            - name: EUREKA_SERVICE_URI
              value: "http://discovery-service:8761/eureka/"
          resources:
            requests:
              memory: "400Mi"
              cpu: "250m"
            limits:
              memory: "800Mi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 10

      restartPolicy: Always
      