apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  ports:
    - port: 8765
      name: gateway-service

  type: LoadBalancer
  selector:
    app: gateway-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      name: gateway-service
      labels:
        app: gateway-service
    spec:
      priorityClassName: "high-priority"
      containers:
        - name: gateway-service
          image: jubastik/29_backend_t1
          command: [ "java", "-jar", "/app/gateway-service.jar" ]
          ports:
            - containerPort: 8761
          env:
            - name: CONFIG_SERVICE_URI
              value: "http://config-service:8888"
            - name: CONFIG_SERVICE_USER
              valueFrom:
                secretKeyRef:
                  name: config-secret
                  key: username
            - name: CONFIG_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-secret
                  key: password

            - name: GATEWAY_SERVICE_PORT
              value: "8765"
            - name: EUREKA_SERVICE_URI
              value: "http://discovery-service:8761/eureka/"
          resources:
            requests:
              memory: "700Mi"
              cpu: "250m"
            limits:
              memory: "1200Mi"
              cpu: "700"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8765
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8765
            initialDelaySeconds: 10

      restartPolicy: Always
      